# =========================
# Server
# =========================
server.port=8080

# =========================
# Datasource (MySQL)
# - Docker에서는 docker-compose의 SPRING_DATASOURCE_* 환경변수가 이 값을 덮어씀
# - 로컬에서는 기본값(localhost)을 사용
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/lesdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# (선택) MySQL 8 권장 Dialect 자동추론이 되지만, 필요하면 고정 가능
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# =========================
# Logging (선택)
# =========================
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

#로컬 테스트용
spring.docker.compose.enabled=true

#루트에 있는 컴포즈 파일 읽기
spring.docker.compose.file=../../docker-compose.yml