version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PW}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_ID=${MYSQL_ID}
      - MYSQL_PW=${MYSQL_PW}
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
